dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DATABASE_HOME_HOST') }}"
      user: "{{ env_var('DATABASE_USER') }}"
      password: "{{ env_var('DATABASE_PASSWORD') }}"
      port: "{{ env_var('DATABASE_PORT') | int }}"
      dbname: "{{ env_var('DATABASE_NAME') }}"
      schema: dbt_dev
    prod:
      type: postgres
      host: "{{ env_var('DATABASE_AWAY_HOST') }}"
      user: "{{ env_var('DATABASE_USER') }}"
      password: "{{ env_var('DATABASE_PASSWORD') }}"
      port: "{{ env_var('DATABASE_PORT') | int }}"
      dbname: "{{ env_var('DATABASE_NAME') }}"
      schema: dbt