dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: 75.155.166.60 #192.168.1.67
      user: dbt_user
      password: N8r!vPx73@kdLaWz5#Ft
      port: 5432
      dbname: postgres
      schema: dbt
    prod:
      type: postgres
      host: 75.155.166.60
      user: dbt_user
      password: N8r!vPx73@kdLaWz5#Ft
      port: 5432
      dbname: postgres
      schema: dbt