version: 2

sources:
  - name: digital_bank
    tables:
    - name: dim_user
    - name: dim_trustpilot_reviews
    - name: dim_registration_source
    - name: dim_event_onboarding
    - name: dim_monetary_account
    - name: dim_invoice_item
  - name: stocks
    tables:
      - name: nyse_stocks